name: Deploy to Hostinger

on:
  push:
    branches:
      - main # The branch name your are commit the new changes
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" # Adjust to your PHP version

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-scripts

      - name: Prepare Laravel App
        run: |
          cp .env.example .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          php artisan key:generate

      - name: Setup Project
        run: |
          mkdir -p storage/logs
          sudo chown -R $USER:www-data storage
          sudo chmod -R 775 storage
          php artisan route:clear
          php artisan config:clear

      - name: Run migrations
        run: php artisan migrate

      - name: Run post-install scripts
        run: composer run-script post-autoload-dump

      # - name: Deploy
      #   uses: s0/git-publish-subdir-action@develop
      #   env:
      #     REPO: self
      #     BRANCH: main # The branch name where you want to push the assets
      #     FOLDER: . # The directory where your assets are generated
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
      #     MESSAGE: "Build: ({sha}) {msg}" # The commit message
      - name: Deploy to Hostinger
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: ${{ secrets.HOSTINGER_PORT }} # Add this line
          source: "." # The directory you want to copy
          target: "public_html/flutterando" # The directory on the Hostinger server where you want to put the files

